language: generic
sudo: required
services:
 - docker
install: true

before_install:
- export
- chmod +x .travis/*.sh

jobs:
  include:
    - stage: Build and deploy
      script:
        - "./.travis/build-and-deploy.sh"

env:
  global:
  - secure: "LletnkOBdTIbk1yMZX2m0tHh5v2d+3qKaAVktRphkxdAHgjwsElqPGiTgm3VuGDpyPJQcUXRqyyTtdaUyQKhqCU8jIKAH0kaVpSdpXIvAE0ivqVUWlWM0dFQSbCv1lbPasW7/6da+1tDoZrJX+pwtpnI3BSmfiGx8qGv+QybwcBZF4qNTRJaGOxpuxbWF8/e0IM7wDhnbSi55OrByY+6eEyEMY9WKjqku2TJ+hPQVuleeZ9f7JlJz3QyyX70+I4byZePiof6grSjqyllsdYeMOl5HZwjvTvbcI0hkpwjmeiKGNSJbRDtWkF28M8tHgnWjhdIOD/FYh9WHBkyiTJUl3bWkguYw6WKEwcBukm8aLd9csOVKbchh3jRTKC6GcJ3pGOqpNWLFcPrT70oj7xcrmOQcD35d47kJqgmhZrCXGgVaxVX8I4lRXRh/HyYKtlajhuOIBSYhCzP1OifWbR5RFb9PUNFDHyVkwuJYCoL5DSFviKHL/sYxSVlcfdFQNci53loW4YkmDE4EVLPpqUJm4Yt7odbR3BIgucglRbMRAKfZsFWXchxVjkEnGgc/HextwFVEyN4bqoorAbB7hseDjLo/PPbuO5fJ6hlz4RjawkWzani2/npigXQgjGW+pz/xrimmZUFp8SFYWeV3DBcQSi+MIBb/wSQyvT825TAIJw="
    # ^^ DOCKER_IO_USERNAME
  - secure: "tWGilNuHw7Maa9CW15fMvesATAZV8hjwrmeeCLZ8LRNTrkUKOTZhj5Bfb78ljXpwXUnvymI0Ku9xXI1HyYKx9g2UmVEOnkDDrkU9vMIOGhAn88v4f/niUuRrxLJTOQuyEXdI/zi9sJ0OuGa4Jmle3cwjDmc7Hv61LpXaNiZslDYq83P6xGnKg5wWL9GxkCtegVAdPIaGYSGYK2t0KPZ9c7I8tjjgPyw8JdSNg4c62RiN+nqF9T+Pzg4h/3k8piJsRc4vEGLEDYtxn4pD2swWfhQExAm5VFmPvGynuxOaM9jJGz5uLw32Cq74C5zjnju7r/XyjSVwZmu5e6PsHQJSTcbjvJlah4j9oEK0wXX2LpaF8wenHmCp0wIehRwpTuIdES432f9KOqpVW00wi7I6MlI0xOf+UDFEox6+xnVJjy1dU8KWJrE597RKawBHE80d6Df3dbzcNNfufCNCE8juhykd4p/t1UrdnvNca3OiYgKoLTIOD0VWTTrJdv8NE/RWK16Kvn5cYdl+A0IG+oc1DGcpp6Uyiao0CGjZggxzpq6Zrncd4T45FowiYnWRKO07Ju1a1cg2ufwyn/zSBQB6HnJZV8fBijFe7ZDXkVWoc58LkS9CFkCcLjR7ErWruXSB0dwupHbsnm2tf7iO0SkyG9CKYjuh6YW03vjYh8SKyMY="
  - # ^^ DOCKER_IO_TOKEN
